### ISSUE TITLE
printing problem 

### ISSUE THREAD

**Issue by emman122** [saper-2/crystalreports-code128#1]
hello, there is a problem when printing either to a thermal or a pdf file, the barcode comes out with strange symbols, it is strange in the viewer, it is correct
![image](https://user-images.githubusercontent.com/39506195/173979360-cdb9bf11-9ddf-43fb-8f0e-f1d677c84a5a.png)

**Comment by saper-2** [comment]
I can think of 2 things:
* Those are "undefined" character in font file. Are you set right font? 
* There is something with the code when using numbers only (are you?) - then might be better to use Code39 or 93 in that case (just before and after number add ```*```, e.g. number 2345 should have in TextObject value: ```*2345*``` 

This font have under character code 208..210 start symbols for Code-128 symbology, maybe either your OS not handling the font properly or your CR version.

Try removing (uninstalling or whatever it is called) from windows font. Reboot, install into windows the font file I have attached with this repo. I don't have any other ideas...

I'd need to check how it behave when there are only numbers 🤔

**Comment by MichalSobierajski** [comment]
Hi, I encountered an identical problem.
Blank spaces at the beginning and end of the code.
Have you been able to solve it?

**Comment by simchev** [comment]
For anyone having the blank spaces problem, it most likely means you're using a common encoding font, and this repo is for the uncommon encoding. You can use my forked version for the common encoding here: https://github.com/simchev/crystalreports-code128

**Comment by batintherain** [comment]
> For anyone having the blank spaces problem, it most likely means you're using a common encoding font, and this repo is for the uncommon encoding. You can use my forked version for the common encoding here: https://github.com/simchev/crystalreports-code128

Hi, I had the same problem on CR 9.2.2 and your fork worked on my developing machine. I don't really get the difference between common and uncommon encoding though. 
I wonder if the Code128.ttf v2.0 is still the only "extra" prerequisite for clients. 
Thanks anyway!

**Comment by saper-2** [comment]
added @simchev repo ref in readme.md at and with explanation when to use it. Also ref this issue for more info.
